namespace TestAp.ExceptionsHandling.Finally
{
    public class FinallyWorks
    {
        static int count = 0;

        //public static void Main() 
        //{
        //    while (true)
        //    {
        //        try
        //        {
        //            if (count ++ < 3)
        //            {
        //                throw new ThreeException();
        //            }

        //            Console.WriteLine("No Exception");
        //        }
        //        catch (ThreeException)
        //        {
        //            Console.WriteLine("Three Exception is handled! ");
        //        }
        //        finally 
        //        {
        //            Console.Error.WriteLine("In finally clause");
        //        }

        //        if (count >= 4)
        //        {
        //            break;
        //        }
        //    }
        //}
    }
}
